name: lttb
description: A LTTB downsampling plugin
version: 0.0.1
repository: https://github.com/bnap00/dart-lttb

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
